Repository nijesmik/algo-study-season-1, pull requests merged in 2023-10, with the labels that each got.

#15 [nijesmik] Week05 PR
  nijesmik/Week05/결혼식.java
  nijesmik/Week05/택배 배달과 수거하기/Solution.java
  nijesmik/Week05/회장뽑기.java
Labels: 제출

#17 [Monami123321] Week05 PR
  Monami123321/Week01/백준_2493_탑.java
  Monami123321/Week01/백준_2504_괄호의값.java
  Monami123321/Week02-1/백준_2164_카드2.java
  Monami123321/Week02-1/백준_5397_키로거.java
  Monami123321/Week02-2/백준_1068_트리.java
  Monami123321/Week02-2/백준_15681_트리와쿼리.java
  Monami123321/Week03-1/백준_11501_주식.java
  Monami123321/Week03-1/백준_2170_선긋기.java
  Monami123321/Week03-2/백준_16401_과자나눠주기.java
  Monami123321/Week03-2/백준_18869_멀티버스2.java
  Monami123321/Week04-1/백준_1012_유기농배추.java
  Monami123321/Week04-1/백준_7569_토마토.java
  Monami123321/Week04-2/백준_16987_계란으로계란치기.java
  Monami123321/Week04-2/백준_6603_로또.java
  Monami123321/Week05/백준_2660_회장뽑기.java
  Monami123321/Week05/백준_5567_결혼식.java
  Monami123321/Week05/프로그래머스_택배_배달과_수거하기.java
Labels: 제출, 추가 제출

#20 [damdam6] Week05 PR
  damdam6/Week05-1/결혼식.java
  damdam6/Week05-1/회장뽑기.java
Labels: 지각, 부분 제출

#19 [747Socker] Week05 PR
  747Socker/Week05/결혼식.java
  747Socker/Week05/회장뽑기.java
Labels: 부분 제출

#18 [KimJihwan98] Week05 PR
  KimJihwan98/Week05-1/결혼식.java
  KimJihwan98/Week05-1/회장뽑기.java
Labels: 부분 제출

#23 [nijesmik] Week06 PR
  nijesmik/Week06/계보_복원가_호석.java
  nijesmik/Week06/빙산.java
  nijesmik/Week06/숨바꼭질_3.java
  nijesmik/Week06/음악프로그램.java
  nijesmik/Week06/전력망을_둘로_나누기/Solution.java
Labels: 제출, 수정 완료

#21 [Monami123321] Week06 PR
  Monami123321/Week06-1/백준_21276_계보복원가호석.java
  Monami123321/Week06-1/백준_2623_음악프로그램.java
  Monami123321/Week06-2/백준_13549_숨바꼭질3.java
  Monami123321/Week06-2/백준_2573_빙산.java
  Monami123321/Week06-2/프로그래머스_전력망을_둘로_나누기.java
Labels: 제출

#22 [KimJihwan98] Week06 PR
  KimJihwan98/Week06-1/계보_복원가_호석.java
  KimJihwan98/Week06-1/음악프로그램.java
  KimJihwan98/Week06-2/빙산.java
  KimJihwan98/Week06-2/숨바꼭질3.java
  KimJihwan98/Week06-2/전력망을_둘로_나누기.java
Labels: 제출

#24 [damdam6] Week06 PR
  damdam6/Week06-1/계보_복원가_호석.java
  damdam6/Week06-1/음악프로그램.java
  damdam6/Week06-2/빙산.java
  damdam6/Week06-2/숨바꼭질_3.java
  damdam6/Week06-2/전력망을_둘로_나누기.java
Labels: 제출, 수정 완료

#25 [747Socker] Week06 PR
  747Socker/Week06/계보_복원가_호석.java
  747Socker/Week06/빙산.java
  747Socker/Week06/숨바꼭질3.java
  747Socker/Week06/음악프로그램.java
  747Socker/Week06/전력망을_둘로_나누기.java
  FETCH_HEAD
Labels: 부분 제출

#27 [damdam6] Week07 PR
  damdam6/Week07-1/광물_캐기.java
  damdam6/Week07-1/불.java
  damdam6/Week07-1/적록색약.java
  damdam6/Week07-2/로봇_청소기.java
  damdam6/Week07-2/뱀.java
Labels: 제출

#29 [nijesmik] Week07 PR
  nijesmik/Week07/광물_캐기/Solution.java
  nijesmik/Week07/로봇_청소기.java
  nijesmik/Week07/뱀.java
  nijesmik/Week07/불.java
  nijesmik/Week07/적록색약.java
Labels: 제출, 수정 완료

#28 [KimJihwan98] Week07 PR
  KimJihwan98/Week07-1/불.java
  KimJihwan98/Week07-1/적록색약.java
  KimJihwan98/Week07-2/광물_캐기.java
  KimJihwan98/Week07-2/로봇_청소기.java
  KimJihwan98/Week07-2/뱀.java
Labels: 제출, 수정 완료

#30 [747Socker] Week07 PR
  747Socker/Week07-1/불.java
  747Socker/Week07-1/적록색약.java
  747Socker/Week07-2/광물_캐기.java
  747Socker/Week07-2/로봇_청소기.java
  747Socker/Week07-2/뱀.java
Labels: 🐆 제출, ✅ 수정 완료

#31 [Monami123321] Week08 PR
  Monami123321/Week08-1/백준_16398_행성연결.java
  Monami123321/Week08-1/백준_1774_우주신과의교감.java
  Monami123321/Week08-2/백준_1238_파티.java
  Monami123321/Week08-2/백준_1504_특정한최단경로.java
  Monami123321/Week08-2/프로그래머스_빛의경로사이클.java
Labels: 🐆 제출

#33 [nijesmik] Week08 PR
  nijesmik/Week08/빛의_경로_사이클/Solution.java
  nijesmik/Week08/우주신과의_교감.java
  nijesmik/Week08/특정한_최단_경로.java
  nijesmik/Week08/파티.java
  nijesmik/Week08/행성_연결.java
Labels: 🐆 제출

#35 [KimJihwan98] Week08 PR
  KimJihwan98/Week08-1/우주신과의_교감.java
  KimJihwan98/Week08-1/행성_연결.java
  KimJihwan98/Week08-1/행성_연결_크루스칼.java
  KimJihwan98/Week08-2/빛의_경로_사이클.java
  KimJihwan98/Week08-2/특정한_최단_경로.java
  KimJihwan98/Week08-2/파티.java
Labels: 🐆 제출

#34 [damdam6] Week08 PR
  damdam6/Week08-1/우주신과의_교감.java
  damdam6/Week08-1/행성_연결.java
  damdam6/Week08-1/행성_연결_크루스칼.java
  damdam6/Week08-2/빛의_경로_사이클.java
  damdam6/Week08-2/특정한_최단_경로.java
  damdam6/Week08-2/파티.java
Labels: 🐆 제출

#37 [nijesmik] Week09 PR
  nijesmik/Week09/아기_상어.java
  nijesmik/Week09/청소년_상어.java
  nijesmik/Week09/퇴사_2.java
  nijesmik/Week09/팰린드롬.java
  nijesmik/Week09/후보키/Solution.java
Labels: 🐆 제출

#38 [damdam6] Week09 PR
  damdam6/Week09-1/퇴사_2.java
  damdam6/Week09-1/팰린드롬.java
  damdam6/Week09-2/아기_상어.java
  damdam6/Week09-2/청소년_상어.java
  damdam6/Week09-2/후보키.java
Labels: 🐆 제출

#39 [Monami123321] Week09 PR
  Monami123321/Week09-1/백준_10942_펠린드롬.java
  Monami123321/Week09-1/백준_15486_퇴사2.java
  Monami123321/Week09-2/백준_16236_아기상어.java
  Monami123321/Week09-2/백준_19236_청소년상어.java
  Monami123321/Week09-2/프로그래머스_후보키.java
Labels: 🐆 제출
